#!/usr/bin/env bash

set -o errexit
set -o pipefail

lint() {
  # Lint all supported file types
  local cmd=(shellcheck)

  if ! command -v shellcheck >/dev/null 2>&1; then
    local cmd=(docker container run --rm -i -v "${PWD}:/mnt" koalaman/shellcheck:stable)
  fi

  find . -type f \
    ! -path "./.git/*" \
    ! -path "./.ruff_cache/*" \
    ! -path "./.pytest_cache/*" \
    ! -path "./c/*" \
    -exec grep --quiet -E '^(#!.*sh|# shellcheck shell=)' {} \; -exec "${cmd[@]}" {} +

  ruff check "${@}"
}

format() {
  # Format all supported file types.
  shfmt --write .

  ruff check --fix
  ruff format "${@}"
}

quality() {
  # Perform all code quality commands together.
  lint "${@}"
  format "${@}"
}

help() {
  printf "%s <task> [args]\n\nTasks:\n" "${0}"

  compgen -A function | grep -v "^_" | cat -n

  printf "\nExtended help:\n  Each task has comments for general usage\n"
}

TIMEFORMAT=$'\nTask completed in %3lR'
time "${@:-help}"
