# By default this waits for every network device and times out after 120s.
#
# Here's how 120s can be annoying when booting up and why I changed it to 10s:
#
# LAPTOP (wifi):
#  When traveling, if you're in a location and you haven't configured wifi yet.
#
# DESKTOP (ethernet):
#  Your power goes out and your machine boots up faster than your router.
#
# If you have a network mounted drive in fstab and it takes longer than 10s to
# connect you can configure it to mount on first access instead of on boot.
[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --any --timeout=10
