#!/usr/bin/env bash
# Customize these in the config file instead of editing them here.

export DEFAULT_CONFIG_INSTALL=(
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/bat/config\" \"\${XDG_CONFIG_HOME}/bat/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/btop/btop.conf\" \"\${XDG_CONFIG_HOME}/btop/btop.conf\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/fzf/config.sh\" \"\${XDG_CONFIG_HOME}/fzf/config.sh\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/ghostty/config.local\" \"\${XDG_CONFIG_HOME}/ghostty/config.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/ghostty/config\" \"\${XDG_CONFIG_HOME}/ghostty/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/git/config.local\" \"\${XDG_CONFIG_HOME}/git/config.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/git/config\" \"\${XDG_CONFIG_HOME}/git/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/gnupg/gpg-agent.conf\" \"\${XDG_CONFIG_HOME}/gnupg/gpg-agent.conf\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/nvim\" \"\${XDG_CONFIG_HOME}/nvim\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/tmux/tmux.conf\" \"\${XDG_CONFIG_HOME}/tmux/tmux.conf\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.aliases.local\" \"\${XDG_CONFIG_HOME}/zsh/.aliases.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.aliases\" \"\${XDG_CONFIG_HOME}/zsh/.aliases\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.xdg.local\" \"\${XDG_CONFIG_HOME}/zsh/.xdg.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.zprofile.local\" \"\${XDG_CONFIG_HOME}/zsh/.zprofile.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.zprofile\" \"\${XDG_CONFIG_HOME}/zsh/.zprofile\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.zshenv\" \"\${HOME}/.zshenv\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.zshrc.local\" \"\${XDG_CONFIG_HOME}/zsh/.zshrc.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zsh/.zshrc\" \"\${XDG_CONFIG_HOME}/zsh/.zshrc\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/bin/\"* \"\${HOME}/.local/bin/\""
)

export DEFAULT_CONFIG_INSTALL_GUI_LINUX=(
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/elephant\" \"\${XDG_CONFIG_HOME}/elephant\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/fontconfig/fonts.conf\" \"\${XDG_CONFIG_HOME}/fontconfig/fonts.conf\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/mako/config.local\" \"\${XDG_CONFIG_HOME}/mako/config.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/mako/config\" \"\${XDG_CONFIG_HOME}/mako/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/mimeapps.list\" \"\${XDG_CONFIG_HOME}/mimeapps.list\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/mpd/mpd.conf\" \"\${XDG_CONFIG_HOME}/mpd/mpd.conf\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/mpv\" \"\${XDG_CONFIG_HOME}/mpv\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/niri/config.kdl.local\" \"\${XDG_CONFIG_HOME}/niri/config.kdl.local\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/niri/config.kdl\" \"\${XDG_CONFIG_HOME}/niri/config.kdl\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/rmpc/config.ron\" \"\${XDG_CONFIG_HOME}/rmpc/config.ron\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/satty/config.toml\" \"\${XDG_CONFIG_HOME}/satty/config.toml\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/swayidle/config\" \"\${XDG_CONFIG_HOME}/swayidle/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/swaylock/config\" \"\${XDG_CONFIG_HOME}/swaylock/config\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/tumbler/tumbler.rc\" \"\${XDG_CONFIG_HOME}/tumbler/tumbler.rc\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/uwsm/env\" \"\${XDG_CONFIG_HOME}/uwsm/env\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/walker/config.toml\" \"\${XDG_CONFIG_HOME}/walker/config.toml\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/walker/themes/base/style.css\" \"\${XDG_CONFIG_HOME}/walker/themes/base/style.css\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/waybar/config.jsonc\" \"\${XDG_CONFIG_HOME}/waybar/config.jsonc\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/waybar/style.css\" \"\${XDG_CONFIG_HOME}/waybar/style.css\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/xarchiver/xarchiverrc\" \"\${XDG_CONFIG_HOME}/xarchiver/xarchiverrc\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.config/zathura/zathurarc\" \"\${XDG_CONFIG_HOME}/zathura/zathurarc\""
  "ln -fns \"\${DOTFRIEDRICE_PATH}/.local/share/applications/\"* \"\${XDG_DATA_HOME}/applications/\""
  "sudo ln -fns \"\${DOTFRIEDRICE_PATH}/etc/systemd/system/systemd-networkd-wait-online.service.d/99-network-timeout.conf\" \"/etc/systemd/system/systemd-networkd-wait-online.service.d/99-network-timeout.conf"\"
)

export DEFAULT_CONFIG_INSTALL_ARCH=(
  "sudo ln -fns \"/run/systemd/resolve/stub-resolv.conf\" \"/etc/resolv.conf\""
  "sudo ln -fns \"\${DOTFRIEDRICE_PATH}/etc/conf.d/pacman-contrib\" \"/etc/conf.d/pacman-contrib\""
  "sudo ln -fns \"\${DOTFRIEDRICE_PATH}/etc/pacman.d/01-options.conf\" \"/etc/pacman.d/01-options.conf\""
)

export DEFAULT_CONFIG_INSTALL_WSL=(
  "cp \"\${DOTFRIEDRICE_PATH}/mnt/c/Users/Nick/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json\" \"/mnt/c/Users/%WindowsUser/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json\" || true"
  "sudo ln -fns \"\${DOTFRIEDRICE_PATH}/etc/wsl.conf\" \"/etc/wsl.conf\""
)
