#!/usr/bin/env bash
# Customize these in the config file instead of editing them here.

export DEFAULT_SCRIPTS_INSTALL=(
  "https://raw.githubusercontent.com/nickjj/bmsu/0.5.1/src/bmsu|--version"
  "https://raw.githubusercontent.com/nickjj/invoice/v0.1.3/invoice|--version"
  "https://raw.githubusercontent.com/nickjj/lcurl/0.1.2/lcurl|--version"
  "https://raw.githubusercontent.com/nickjj/notes/v0.3.1/notes|--version"
  "https://raw.githubusercontent.com/nickjj/plutus/0.7.3/src/plutus|--version"
  "https://raw.githubusercontent.com/nickjj/wait-until/v0.3.1/wait-until|--version"
  "https://raw.githubusercontent.com/nickjj/webserver/v0.4.2/webserver|--version"
)
