theme = "base"
additional_theme_location = "./themes/base"

[keybinds]
quick_activate = []

[providers]
default = ["desktopapplications"]

[providers.clipboard]
time_format = "%b %d %y :: %I:%M %p"

[columns]
"menus:keybinds" = 2
